name: Etherpad Docker Image

env:
  REGISTRY: ghcr.io
  PROJECTNAME: etherpad
  
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - '${{env.PROJECTNAME}}/*'
      - '.github/workflows/*${{env.PROJECTNAME}}*'
  pull_request:
    branches: ['main']
    paths:
      - '${{env.PROJECTNAME}}/*'
      - '.github/workflows/*${{env.PROJECTNAME}}*'
  schedule:
    - cron: '23 1 * * 0'  # Sunday at 1:23

jobs:
  include:
    - name: Build and Push Image
      uses: ./.github/templates/docker-build-template.yml
