
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          RELEASE_DATE=$(date --rfc-3339=date)
          IMAGE_NAME="${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PROJECTNAME }}"
          
          docker build -t $IMAGE_NAME:$RELEASE_DATE -t $IMAGE_NAME:latest ./${{ env.PROJECTNAME}}/
          docker push $IMAGE_NAME:$RELEASE_DATE
          docker push $IMAGE_NAME:latest

